apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaUser
metadata:
  name: kafka-connect-credentials
  labels:
    eventstreams.ibm.com/cluster: es
spec:
  authentication:
    # generate username/password for this user
    type: scram-sha-512
  authorization:
    acls:
      # ---------------------------------------
      # cluster permissions
      # ---------------------------------------
      # check existing cluster config
      - operation: DescribeConfigs
        resource:
          type: cluster
      # ---------------------------------------
      # topic permissions
      # ---------------------------------------
      # check existing topics
      - operation: DescribeConfigs
        resource:
          name: '*'
          patternType: literal
          type: topic
      # create topics (both to produce to, and to use for internal state)
      - operation: Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      # consume from topics (needed to retrieve state from internal topics)
      - operation: Read
        resource:
          name: '*'
          patternType: literal
          type: topic
      # produce to topics (both writing to internal state topics and messages being produced by connectors)
      - operation: Write
        resource:
          name: '*'
          patternType: literal
          type: topic
      # ---------------------------------------
      # consumer group permissions
      # ---------------------------------------
      - operation: Read
        resource:
          name: '*'
          patternType: literal
          type: group
      # ---------------------------------------
      # transaction permissions
      # ---------------------------------------
      # create transactions
      - operation: Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
