apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: flight-takeoffs
  labels:
    eventstreams.ibm.com/cluster: es
spec:
  config:
    min.insync.replicas: '1'
    retention.ms: '101606400000'
  partitions: 1
  replicas: 3
  topicName: FLIGHT.TAKEOFFS
